[package]
name = "fmm-c"
description = "C backend for F--"
version = "0.1.0"
license = "MIT"
authors = ["Yota Toyama <raviqqe@gmail.com>"]
edition = "2018"

[dependencies]
fmm = { path = "../fmm" }
tempfile = "3"
