[package]
name = "fmm"
description = "F-- programming language"
version = "0.1.0"
license = "MIT"
authors = ["Yota Toyama <raviqqe@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1"
petgraph = "0.5"
